# numpy库学习

`Numpy` 是 Python 的一个科学计算库，它提供了支持多维数组和矩阵运算的功能，此外还包含大量数学函数库。以下是 Numpy 的基本用法和一些常见的操作示例。

---

### 1.安装 Numpy

In [ ]:
pip install numpy

---

### 2. 导入 Numpy

In [2]:
import numpy as np

---

### 3.Numpy 数组

In [4]:
import numpy as np

# 从列表创建数组
array1 = np.array([1, 2, 3, 4, 5])
print("array1:", array1)

# 创建全零数组
array2 = np.zeros((3, 4))
print("array2:\n", array2)

# 创建全一数组
array3 = np.ones((2, 3))
print("array3:\n", array3)

# 创建一个范围内的数组
array4 = np.arange(0, 10, 2)  # 从0到10（不包括10），步长为2
print("array4:", array4)

# 创建一个线性间隔的数组
array5 = np.linspace(0, 1, 5)  # 从0到1，分成5个均匀间隔
print("array5:", array5)


array1: [1 2 3 4 5]
array2:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
array3:
 [[1. 1. 1.]
 [1. 1. 1.]]
array4: [0 2 4 6 8]
array5: [0.   0.25 0.5  0.75 1.  ]


In [5]:
array = np.array([[1, 2, 3], [4, 5, 6]])
print("数组形状:", array.shape)
print("数组维度:", array.ndim)
print("数组元素类型:", array.dtype)
print("数组大小:", array.size)
print("数组每个元素的字节大小:", array.itemsize)


数组形状: (2, 3)
数组维度: 2
数组元素类型: int64
数组大小: 6
数组每个元素的字节大小: 8


---

### 4. 数组操作

In [6]:
array = np.array([1, 2, 3, 4, 5])
print("数组的第一个元素:", array[0])
print("数组的前三个元素:", array[:3])
print("数组的最后两个元素:", array[-2:])


数组的第一个元素: 1
数组的前三个元素: [1 2 3]
数组的最后两个元素: [4 5]


In [7]:
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("第0行第1列的元素:", array[0, 1])
print("第1行的所有元素:", array[1, :])
print("所有行的第2列的元素:", array[:, 2])


第0行第1列的元素: 2
第1行的所有元素: [4 5 6]
所有行的第2列的元素: [3 6 9]


In [8]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

print("数组加法:", array1 + array2)
print("数组减法:", array1 - array2)
print("数组乘法:", array1 * array2)
print("数组除法:", array1 / array2)
print("数组平方:", array1 ** 2)


数组加法: [5 7 9]
数组减法: [-3 -3 -3]
数组乘法: [ 4 10 18]
数组除法: [0.25 0.4  0.5 ]
数组平方: [1 4 9]


---

### 5.常用函数

In [9]:
array = np.array([1, 2, 3, 4, 5])

print("数组求和:", np.sum(array))
print("数组平均值:", np.mean(array))
print("数组最大值:", np.max(array))
print("数组最小值:", np.min(array))
print("数组标准差:", np.std(array))


数组求和: 15
数组平均值: 3.0
数组最大值: 5
数组最小值: 1
数组标准差: 1.4142135623730951


In [15]:
# 生成一个0到1之间的随机数
random_number = np.random.random()
print("随机数:", random_number)

# 生成一个形状为(2, 3)的数组，包含0到1之间的随机数
random_array = np.random.random((2, 3))
print("随机数组:\n", random_array)

# 生成一个均值为0，标准差为1的正态分布随机数
normal_array = np.random.normal(0, 1, (2, 3))
print("正态分布随机数组:\n", normal_array)


随机数: 0.7808382426221533
随机数组:
 [[0.04074339 0.12207368 0.02615567]
 [0.80889353 0.77532042 0.56128505]]
正态分布随机数组:
 [[-1.54364089 -0.57087515  0.05001329]
 [ 0.64452447  0.9492622  -1.02576692]]


In [16]:
array = np.array([[1, 2, 3], [4, 5, 6]])
reshaped_array = array.reshape((3, 2))
print("原始数组:\n", array)
print("变形后的数组:\n", reshaped_array)
#数组变形

原始数组:
 [[1 2 3]
 [4 5 6]]
变形后的数组:
 [[1 2]
 [3 4]
 [5 6]]


---

### 6.示例代码

In [17]:
import numpy as np

# 创建一个数组
array = np.array([1, 2, 3, 4, 5])

# 进行一些基本运算
sum_result = np.sum(array)
mean_result = np.mean(array)
max_result = np.max(array)

print("数组求和:", sum_result)
print("数组平均值:", mean_result)
print("数组最大值:", max_result)

# 创建一个随机数组
random_array = np.random.random((3, 3))
print("随机数组:\n", random_array)

# 对随机数组进行形状变换
reshaped_array = random_array.reshape((1, 9))
print("变形后的数组:\n", reshaped_array)


数组求和: 15
数组平均值: 3.0
数组最大值: 5
随机数组:
 [[0.45685209 0.45667962 0.86717688]
 [0.99301679 0.05352161 0.76085266]
 [0.19614348 0.29940022 0.95820277]]
变形后的数组:
 [[0.45685209 0.45667962 0.86717688 0.99301679 0.05352161 0.76085266
  0.19614348 0.29940022 0.95820277]]
